<?php

namespace AppBundle\Repository;

/**
 * ComGeneralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComGeneralRepository extends \Doctrine\ORM\EntityRepository
{
}
