<?php

namespace AppBundle\Repository;

/**
 * ComOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
