<?php

namespace AppBundle\Repository;

/**
 * GaleriePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriePhotoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des photos par ordre decroissant
     */
    public function findListDesc($statut = null)
    {
        if ($statut){
            return $this->createQueryBuilder('p')
                        ->where('p.statut = 1')->orderBy('p.id', 'DESC')->getQuery()->getResult();
        }else{
            return $this->createQueryBuilder('p')
                        ->orderBy('p.id', 'DESC')->getQuery()->getResult();
        }
    }
}
