<?php

namespace AppBundle\Repository;

/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des albums photos par ordre alphabetique
     */
    public function findList($statut = null)
    {
        if ($statut){
            return $this->createQueryBuilder('g')
                        ->where('statut = 1')->orderBy('g.titre', 'ASC');/*->getQuery()->getResult();*/
        }else{
            return $this->createQueryBuilder('g')
                        ->orderBy('g.titre', 'ASC');
            //->getQuery()->getResult();
        }
    }
}
