<?php

namespace AppBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des informations
     */
    public function findListDesc($limit=null, $offset=null)
    {
        return $this->createQueryBuilder('i')
                    ->orderBy('i.id', 'DESC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Liste des information actives
     */
    public function findList($limit = null, $offset = null)
    {
        return $this->createQueryBuilder('i')
                    ->where('i.statut = 1')
                    ->andWhere(':date BETWEEN i.datedeb AND i.datefin')
                    ->orderBy('i.datefin', 'ASC')
                    ->setParameter('date', date('Y-m-d', time()))
                    ->getQuery()->getResult()
            ;
    }
}
