<?php

namespace AppBundle\Repository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findList($statut = null)
    {
        if ($statut){
            return $this->createQueryBuilder('s')->where('s.statut = 1')->orderBy('s.id', 'DESC')->getQuery()->getResult();
        }else{
            return $this->createQueryBuilder('s')->orderBy('s.id', 'DESC')->getQuery()->getResult();
        }
    }
}
