<?php

namespace AppBundle\Repository;

/**
 * TourismeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourismeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * La liste des site touristique
     */
    public function findList()
    {
        return $this->createQueryBuilder('t')
                    ->where('t.statut = 1')
                    ->orderBy('t.libelle', 'ASC')
            ;
    }
}
