<?php

namespace AppBundle\Repository;

/**
 * TypePresidenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePresidenceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des titres
     */
    public function findList()
    {
        return $this->createQueryBuilder('t')
                    ->orderBy('t.libelle', 'ASC')
            ;
    }
}
